COLUMNS:
    year: int64
    make: object
    model: object
    trim: object
    body: object
    transmission: object
    vin: object
    state: object
    condition:  float64
    odometer: float64
    color: object
    interior: object
    seller: object
    mnr: float64
    saledate: object

TARGET_COLUMN: 
    sellingprice: float64